.PHONY: clean

all: exercicio_lista_simples exercicio_lista_dupla

exercicio_lista_simples: exercicio_lista_simples.c
	gcc -o exercicio_lista_simples exercicio_lista_simples.c

exercicio_lista_dupla: exercicio_lista_dupla.c
	gcc -o exercicio_lista_dupla exercicio_lista_dupla.c

clean:
	rm exercicio_lista_simples
	rm exercicio_lista_dupla
